"use client";

import { useState } from "react";
import { Button, Card, CardBody, Modal, ModalContent, ModalHeader, ModalBody, ModalFooter } from "@heroui/react";
import { Sparkles, X } from "lucide-react";
import { Heading } from "@/components/ui/Heading";
import { Text } from "@/components/ui/Text";

interface AISummarizeProps {
  content: string;
  title: string;
}

export default function AISummarize({ content, title }: AISummarizeProps) {
  const [summary, setSummary] = useState<string>("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string>("");
  const [isOpen, setIsOpen] = useState(false);

  const handleSummarize = async () => {
    setIsLoading(true);
    setError("");
    setSummary("");

    try {
      const response = await fetch("/api/ai/summarize", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ content, title }),
      });

      const data = await response.json();

      if (data.success) {
        setSummary(data.data.summary);
        setIsOpen(true);
      } else {
        setError(data.message || "Failed to summarize article");
      }
    } catch (err) {
      console.error("Summarize error:", err);
      setError("An error occurred while summarizing");
    } finally {
      setIsLoading(false);
    }
  };

  const handleClose = () => {
    setIsOpen(false);
  };

  return (
    <div>
      {/* Summarize Button or View Button */}
      <Button
        color="primary"
        variant="flat"
        onPress={summary ? () => setIsOpen(true) : handleSummarize}
        isLoading={isLoading}
        isDisabled={isLoading}
        startContent={!isLoading && <Sparkles className="w-4 h-4" />}
        className="w-full sm:w-auto"
      >
        {isLoading ? "AI is Summarizing..." : summary ? "View Summary" : "Summarize with AI"}
      </Button>

      {/* Error Display */}
      {error && (
        <Card className="border-2 border-red-300 dark:border-red-700 mt-3">
          <CardBody>
            <p className="text-red-600 dark:text-red-400 text-sm">{error}</p>
            <Button
              size="sm"
              color="danger"
              variant="flat"
              onPress={() => setError("")}
              className="mt-2"
            >
              Dismiss
            </Button>
          </CardBody>
        </Card>
      )}

      {/* Summary Modal */}
      <Modal isOpen={isOpen} onOpenChange={handleClose} size="2xl" scrollBehavior="inside">
        <ModalContent className="bg-primary-50 dark:bg-primary-950">
          <ModalHeader className="flex items-center gap-2 border-b border-primary-200 dark:border-primary-800">
            <Sparkles className="w-5 h-5 text-primary-600 dark:text-primary-400" />
            <Heading className="font-semibold text-primary-900 dark:text-primary-100">
              AI Summary
            </Heading>
          </ModalHeader>
          <ModalBody className="py-6">
            <div className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-wrap">
              {summary}
            </div>
            <div className="pt-4 border-t border-primary-200 dark:border-primary-800">
              <Text className="text-xs text-gray-500 dark:text-gray-400">
                💡 This summary was generated by AI and may not capture all
                nuances of the article.
              </Text>
            </div>
          </ModalBody>
          <ModalFooter className="border-t border-primary-200 dark:border-primary-800">
            <Button color="primary" onPress={handleClose}>
              Close
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </div>
  );
}
