"use client";

import { useState } from "react";
import { Button, Card, CardBody, Spinner } from "@heroui/react";
import { Sparkles, X } from "lucide-react";
import { Heading } from "@/components/ui/Heading";
import { Text } from "@/components/ui/Text";

interface AISummarizeProps {
  content: string;
  title: string;
}

export default function AISummarize({ content, title }: AISummarizeProps) {
  const [summary, setSummary] = useState<string>("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string>("");
  const [isOpen, setIsOpen] = useState(false);

  const handleSummarize = async () => {
    setIsLoading(true);
    setError("");
    setSummary("");

    try {
      const response = await fetch("/api/ai/summarize", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ content, title }),
      });

      const data = await response.json();

      if (data.success) {
        setSummary(data.data.summary);
        setIsOpen(true);
      } else {
        setError(data.message || "Failed to summarize article");
      }
    } catch (err) {
      console.error("Summarize error:", err);
      setError("An error occurred while summarizing");
    } finally {
      setIsLoading(false);
    }
  };

  const handleClose = () => {
    setIsOpen(false);
    setSummary("");
    setError("");
  };

  return (
    <div className="space-y-4">
      {/* Summarize Button */}
      {!isOpen && (
        <Button
          color="primary"
          variant="flat"
          onPress={handleSummarize}
          isLoading={isLoading}
          isDisabled={isLoading}
          startContent={!isLoading && <Sparkles className="w-4 h-4" />}
          className="w-full sm:w-auto flex flex-1 sm:justify-end"
        >
          {isLoading ? "AI is Summarizing..." : "Summarize with AI"}
        </Button>
      )}

      {/* Error Display */}
      {error && (
        <Card className="border-2 border-red-300 dark:border-red-700">
          <CardBody>
            <p className="text-red-600 dark:text-red-400 text-sm">{error}</p>
            <Button
              size="sm"
              color="danger"
              variant="flat"
              onPress={() => setError("")}
              className="mt-2"
            >
              Dismiss
            </Button>
          </CardBody>
        </Card>
      )}

      {/* Summary Display */}
      {isOpen && summary && (
        <Card className="border-2 border-primary-300 dark:border-primary-700 bg-primary-50 dark:bg-primary-950">
          <CardBody className="space-y-3">
            <div className="flex items-start justify-between gap-2">
              <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-primary-600 dark:text-primary-400 flex-shrink-0" />
                <Heading className="font-semibold text-primary-900 dark:text-primary-100">
                  AI Summary
                </Heading>
              </div>
              <Button
                isIconOnly
                size="sm"
                variant="light"
                onPress={handleClose}
                className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
              >
                <X className="w-4 h-4" />
              </Button>
            </div>

            <div className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-wrap">
              {summary}
            </div>

            <div className="pt-2 border-t border-primary-200 dark:border-primary-800">
              <Text className="text-xs text-gray-500 dark:text-gray-400">
                💡 This summary was generated by AI and may not capture all
                nuances of the article.
              </Text>
            </div>
          </CardBody>
        </Card>
      )}
    </div>
  );
}
